### ISSUE TITLE
4K分辨率UI错位和奇怪布局

### ISSUE THREAD

**Issue by 120910383** [simdsoft/x-studio#202]
开发组有没有考虑4K分辨下的布局呢,感觉工具栏都错位了，字体大小也不对

**Comment by halx99** [comment]
这么牛逼，都用4K屏开发了，我们看看cocos2d-x官方引擎是否支持4K屏

**Comment by 120910383** [comment]
我是说x-studio这个ide，不是开发出的游戏，和cocos引擎没关系吧

**Comment by halx99** [comment]
哦，我以为是渲染界面错位呢，
好的，我们看一下，你显示器分辨率多少，
显示器缩放设置成了多少?

**Comment by 120910383** [comment]
![fenbianlv](https://user-images.githubusercontent.com/5054267/35636461-2558c0e4-06ec-11e8-8fc6-c7d4b8180cf1.jpg)

![qq 20180201010443](https://user-images.githubusercontent.com/5054267/35636406-fb8a4166-06eb-11e8-9475-6dc14e577513.png)

**Comment by 120910383** [comment]
上面只是一个截图，还有一些其他的ui不对，比如左侧三角展开图标，各栏目分界线，和1080p 100%比例的显示不一致

**Comment by halx99** [comment]
dpi有缩放过大， 工具栏 label和combobox确实有问题

**Comment by halx99** [comment]
感觉图标还好

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/114302719-d3c0dc00-9afc-11eb-97b5-5e63aafafa1e.png)
2021版已修复
