### ISSUE TITLE
[Feature Request]macOS version request.

### ISSUE THREAD

**Issue by Evyde** [simdsoft/x-studio#249]
See that this project base on C++, could you compile a mac version? Thx.

**Comment by halx99** [comment]
@ForeverOpp Sorry, Even though, this project is based on C++, but it also based on Windows platform specfiic framework 'MFC' , so, It will be a large project and need cost a long time to port it to macOS.
Current, I think the only one posibble way to port it to macOS is wxWidgets framework.

Tanks for your report.
