### ISSUE TITLE
More control by user for dropping sprites on SpriteSheet.

### ISSUE THREAD

**Issue by halx99** [simdsoft/x-studio#31]
Add 'IsAutoAdjustLayout' for for SpriteSheet properties editing.

**Comment by halx99** [comment]
finished.

**Comment by gplayers** [comment]
if its finished , please update it to next version I have to test and review it. My Current version is:10.0.2210.1

**Comment by halx99** [comment]
Maybe we have a lot of things to work for this issue

**Comment by halx99** [comment]
I think, after we drag & drop a sprite to SpriteSheet, then, the designed level which is using tbe sprite should change reference to SpriteFrame. @gplayers what do u think about this?

**Comment by halx99** [comment]
see reference: 
http://discuss.cocos2d-x.org/t/x-studio365-a-more-powerful-game-develop-ide-support-particlesystem-editing-ui-editing-adapting-preview-spine-animation-preview-support-lua-debug-edit-syntax-highlight-outlinng/29660/119
