### ISSUE TITLE
No member named '_Hash_impl' in namespace 'std' return std::_Hash_impl::hash

### ISSUE THREAD

**Issue by thienphuoc** [simdsoft/x-studio#388]
When i build my project with android platform, I have a problem as follow : 
**No member named '_Hash_impl' in namespace 'std' return std::_Hash_impl::hash**
File : unreal_string.h , Line : 1160 .
`#if defined(__APPLE__)`
            `return std::__do_string_hash(_Keyval.data(), _Keyval.data() + _Keyval.size());`
`#elif defined(__linux__)`
           `return std::_Hash_impl::hash(_Keyval.data(), _Keyval.size() << (sizeof(_Elem) >> 1) );//this line`
`#else`
           ` return _FNV1a_hash(_Keyval.c_str(), _Keyval.size() << ULS_ELEM_SHIFT);`
`#endif`
I have temporarily resolved by commenting this line ! **return std::_Hash_impl::hash(_Keyval.data(), _Keyval.size() << (sizeof(_Elem) >> 1) );**
Here is my cocos2dx and NDK version.
+Cocos2d-x 3.17
+Android-ndk-r16b-windows-x86_64

**Comment by halx99** [comment]
thanks for your report, I will check later.
