### ISSUE TITLE
'Unparrent' option in RMB at object inside Object Explorer.

### ISSUE THREAD

**Issue by gplayers** [simdsoft/x-studio#66]
By pressing Right mouse Button on any object inside 'Object Explorer' we should be able to sent that object in above hierarchy. Same thing we also should be able to do with multiple selection by going in RMB menu.

**Comment by halx99** [comment]
@gplayers Sorry, I don't understand what do you mean？

**Comment by halx99** [comment]
Could you upload some screenshot to explain?
