### ISSUE TITLE
libmpg123.so crash on android 4.2.2 devices

### ISSUE THREAD

**Issue by huachangmiao** [simdsoft/x-studio#691]
**I got this crash stacks on:   vivo Y17T  and   samsung Galaxy Mega 6.3**

Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libmpg123.so" needed by "libcocos2dlua.so"; caused by load_library(linker.cpp:759): library "libmpg123.so" not found
java.lang.Runtime.loadLibrary(Runtime.java:372)

1 java.lang.Runtime.loadLibrary(Runtime.java:382)
2 java.lang.System.loadLibrary(System.java:535)
3 org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Unknown Source)
4 org.cocos2dx.lib.Cocos2dxActivity.onCreate(Unknown Source)
5 org.cocos2dx.lua.AppActivity.onCreate(Unknown Source)
6 android.app.Activity.performCreate(Activity.java:5255)
7 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
8 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
9 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
10 android.app.ActivityThread.access$700(ActivityThread.java:154)
11 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
12 android.os.Handler.dispatchMessage(Handler.java:99)
13 android.os.Looper.loop(Looper.java:137)
14 android.app.ActivityThread.main(ActivityThread.java:5297)
15 java.lang.reflect.Method.invokeNative(Native Method)
16 java.lang.reflect.Method.invoke(Method.java:511)
17 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
18 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
19 dalvik.system.NativeStart.main(Native Method)

**And got this crash stacks in 腾讯手游助手 and 夜神模拟器**

java.lang.UnsatisfiedLinkError

dlopen failed: "/data/app-lib/com.test.xproject.qa-1/libcocos2dlua.so" has unexpected e_machine: 40

**Comment by huachangmiao** [comment]
I think it 's something wrong in libmpg123.so. because I remove the code and libs of the mp3. Then the crash gone.

**Comment by halx99** [comment]
you should load all .so manullay before load main game so

**Comment by halx99** [comment]
our game use the same so, and works well on 夜神模拟器

**Comment by huachangmiao** [comment]
which NDK and SDK versions do you build this so file?

**Comment by halx99** [comment]
ndkr14b gcc apilevel=9

**Comment by huachangmiao** [comment]
thx, I will check it.

**Comment by huachangmiao** [comment]
I use ndkr10d rebuild the libmpg123.a. and every thing is OK.
thank you.
I will close this issue.

**Comment by halx99** [comment]
thx for your feedback
