### ISSUE TITLE
The log output NOT auto scroll follow the latest log.

### ISSUE THREAD

**Issue by troyzhao** [simdsoft/x-studio#818]
The log output window do not auto scroll when it has new log printed. What can i do for that, where is the setting options for that.

Its auto scrolling while start debug, but stop scroll after i clicked the logs.

**Comment by halx99** [comment]
By default, it will auto scroll, when you scroll the log output window manually, will stop auto scroll, then Press `Ctrl + END` to tell editor continue auto scroll to end

**Comment by troyzhao** [comment]
OK, thanks.
